Programação R1.1-1.11
Team-Dire/fctoga pull request #8
Opened 2022-12-15 03:13 UTC by GuiCT

Closes #3

2022-12-21 17:20 UTC, GuiCT commented
Não cheguei a implementar uma UI para teste por conta da dificuldade em usar o GUI Designer do IntelliJ IDEA. Por ora acho que está pronto para merge.

2022-12-21 19:04 UTC, becelli commented
# SQA da programação

Início 18/12/2022 - Fim 21/12/2022

Faltou uma estrutura básica para a realização de testes de software. Pode ser, por exemplo, uma interface gráfica para a execução dos testes, ou um "script" incluindo a possibilidade de cadastrar e recuperar dados.
Como as estruturas ainda são simples, os fiz aqui (não os incluí no Git).

## Programação

| Defeito | Tipo | Descrição                                                                          |
| ------- | ---- | ---------------------------------------------------------------------------------- |
| 01      | FI   | Apesar de raro, nomes não são únicos. Deve-se permitir o cadastro de nomes iguais. |

2022-12-21 19:05 UTC, becelli requested changes
# SQA da programação

Início 18/12/2022 - Fim 21/12/2022

Faltou uma estrutura básica para a realização de testes de software. Pode ser, por exemplo, uma interface gráfica para a execução dos testes, ou um "script" incluindo a possibilidade de cadastrar e recuperar dados.
Como as estruturas ainda são simples, os fiz aqui (não os incluí no Git).

## Programação

| Defeito | Tipo | Descrição                                                                          |
| ------- | ---- | ---------------------------------------------------------------------------------- |
| 01      | FI   | Apesar de raro, nomes não são únicos. Deve-se permitir o cadastro de nomes iguais. |

2022-12-23 16:49 UTC, becelli requested changes
# SQA da programação

Início 18/12/2022 - Fim 23/12/2022

Apesar de prover uma interface, o requisito com defeito não foi consertado.


## Programação

| Defeito | Tipo | Descrição                                                                          |
| ------- | ---- | ---------------------------------------------------------------------------------- |
| 01      | FI   | Apesar de raro, nomes não são únicos. Deve-se permitir o cadastro de nomes iguais. |

2022-12-23 17:30 UTC, GuiCT commented
Tinha esquecido de commitar esse arquivo em específico, agora tá certo.

2022-12-23 17:32 UTC, becelli approved these changes
Aprovado.

2022-12-24 21:30 UTC, merged